adding more logs

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -289,6 +289,7 @@ steps:
         tmpdir=$(mktemp -d)
         trap 'rm -rf -- "$tmpdir"' EXIT SIGTERM
 
+        logBucketName="upgrade-test-container-logs"
         # Update image tags to include the current build version.
         DevVersion="${_BASE_VERSION}-dev-$(git rev-parse --short=7 HEAD)"
         export DevVersion
@@ -380,9 +381,23 @@ steps:
 
             # Wait for the pod to become ready (or timeout)
             if ! kubectl wait --for=condition=ready pod -l job-name=upgrade-test-runner --timeout=5m; then
-              echo "ERROR: Pod for job 'upgrade-test-runner' did not become ready within timeout."
+              echo "ERROR: The pod for job 'upgrade-test-runner' did not become ready within the timeout period."
               job_pod_name=$(kubectl get pods -l job-name=upgrade-test-runner -o jsonpath="{.items[0].metadata.name}")
-              kubectl logs --tail=20 "$job_pod_name" || echo "Could not fetch logs for pod: $job_pod_name"
+              kubectl logs --tail=20 "$job_pod_name" || echo "Unable to retrieve logs for pod: $job_pod_name"
+
+              job_pods=$(kubectl get pods -l job-name=upgrade-test-runner -o jsonpath="{.items[*].metadata.name}")
+
+              for pod in $job_pods; do
+                containers=$(kubectl get pod "$pod" -o jsonpath='{.spec.containers[*].name}')
+                for container in $containers; do
+                  if [[ "$container" == "sdk-client-test" || "$container" == "upgrade-test-controller" ]]; then
+                    echo "----- Logs from pod: $pod, container: $container -----"
+                    kubectl logs "$pod" -c "$container" || echo "Failed to retrieve logs from $pod/$container"
+                  fi
+                done
+              done
+
+              echo "Logs from log bucket: https://console.cloud.google.com/logs/query;storageScope=storage,projects%2F${PROJECT_ID}%2Flocations%2Fglobal%2Fbuckets%2F${logBucketName}%2Fviews%2F_AllLogs;query=$(printf 'resource.labels.container_name=(\"upgrade-test-controller\" OR \"sdk-client-test\")' | jq -sRr @uri);cursorTimestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ);duration=PT10M?project=${PROJECT_ID}"
             fi
 
             echo Wait for job upgrade-test-runner to complete or fail on cluster "${testCluster}"
